version: "3.3"

services:
  B:
    image: vincentserpoul/paritypoa:v2.0.3
    ports:
      - "8547:8547"
      - "8548:8548"
      - "30304:30304"
    environment:
      - JSONRPC_PORT=8547
      - WS_PORT=8548
      - NETWORK_PORT=30304
      - AUTHORITY_COMPANY=B
    volumes:
      - chain_B:/mnt/io.parity.ethereum
    secrets:
      - authority.B.address
      - authority.B.passphrase
      - authority.B.password
    deploy:
      mode: replicated
      replicas: 1
      labels: [NODE=B]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

volumes:
  ? chain_B

networks:
  default:
    external:
      name: poa_default

secrets:
  authority.B.address:
    external: true
  authority.B.passphrase:
    external: true
  authority.B.password:
    external: true
