version: "3.7"

services:
  A:
    image: vincentserpoul/paritypoa:v2.2.2
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    environment:
      - JSONRPC_PORT=8545
      - WS_PORT=8546
      - NETWORK_PORT=30303
    volumes:
      - chain_A:/home/parity/.local/share/io.parity.ethereum
    configs:
      - source: PoA.json
        target: /home/parity/PoA.json
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: configPoANode.A.toml
        target: /home/parity/configPoANode.toml
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: authority.A.address
        target: /home/parity/authority.address
        uid: "1000"
        gid: "1000"
        mode: 0400
    secrets:
      - source: authority.A.priv.json
        target: /run/secrets/authority.priv.json
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: authority.A.password
        target: /run/secrets/authority.password
        uid: "1000"
        gid: "1000"
        mode: 0400
    deploy:
      mode: replicated
      replicas: 1
      labels: [NODE=A]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

volumes:
  chain_A:
    driver_opts:
      o: rw

configs:
  PoA.json:
    external: true
  configPoANode.A.toml:
    external: true
  authority.A.address:
    external: true

secrets:
  authority.A.priv.json:
    external: true
  authority.A.password:
    external: true
